### ISSUE TITLE
MyAnimeList has changed genres

### ISSUE THREAD

**Issue by Katsute** [Katsute/Mal4J#235]
### Prerequisites

- [X] I have checked that no other similar issue already exists.
- [X] I have checked that this issue is actually a bug and not a feature.
- [X] I have checked the [documentation](https://mal4j.katsute.dev/).
- [X] I have checked the [FAQ](https://github.com/Katsute/Mal4J/blob/main/faq.md).
- [X] I am running the latest release version.

### Operating System

ALL

### Java Runtime

Other

### Java Version

ALL

### Release Version

ALL

### Issue

**This issue is high priority**

Genres have changed: https://myanimelist.net/forum/?topicid=1956762

###  Todo

- Replace genre enum with genre class (this will break existing code)

**Comment by Katsute** [comment]
TODO:
- [ ] Fix added/modified/removed genres
- [ ] Prepare codebase for themes (must not use enums)

deprecation will not be used

**Comment by Katsute** [comment]
@sinon-bot branch genre-fix

**Comment by Katsute** [comment]
@sinon-bot branch genre-fix
